name: Minerva
version: '0.1.0'
main: net.minervamc.minerva.Minerva
api-version: '1.21'
commands:
  mskills:
    description: Minerva commands that relate to skills, heritage, and ancestry.
    usage: "\u00A76Correct usage: /mskills [option]"
  skillmode:
    description: Allows you to toggle on and off Minerva's skills system.
    usage: "\u00A76Correct usage: /skillmode"
  party:
    description: Manage parties.
    usage: "\u00A76Correct usage: /party <player>, /party remove <player>, /party list, /party disband"
  permissions:
    minerva.skills.set:
      description: Allows you to set your own stats
    minerva.skills.set.others:
      description: Allows you to set others' stats
      default: op
    minerva.skills.opengui.others:
      description: Allows you to open the Minerva Skills GUI for others.
      default: op
    minerva.bigthree.zeus:
      description: Allows you to choose Zeus in the Skills GUI.
    minerva.bigthree.poseidon:
      description: Allows you to choose Poseidon in the Skills GUI.
    minerva.bigthree.hades:
      description: Allows you to choose Hades in the Skills GUI.
